import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Navbar from "@/components/common/Navbar";
import AnnounceBar from "@/components/common/AnnounceBar";
import { LanguageProvider } from "@/context/LanguageContext";
import { ThemeLanguageProvider } from "@/context/ThemeLanguageContext";
import Footer from "@/components/common/Footer";
import { getAllFalseSales } from "@/utils/FlashSalesApi";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const FlashSale = await getAllFalseSales();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeLanguageProvider>
          <LanguageProvider>
            {FlashSale?.campaign && <AnnounceBar />}
            <Navbar />
            {children}
            <Footer />
          </LanguageProvider>
        </ThemeLanguageProvider>
      </body>
    </html>
  );
}
