import { Roboto } from "next/font/google";
import Providers from "./providers";
import './globals.css'
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased`}>
       
          <Providers>{children}</Providers>
       
      </body>
    </html>
  );
}
